# compose/guac.yml
#
# This file is a synthesized configuration based on the project's original intent
# (Postgres backend, private networking) and the updated service architecture
# introduced in GUAC v1.0.0, as seen in the guac-demo-compose.yaml reference.
#
services:
  guac-postgres:
    image: postgres:13
    container_name: guac-postgres
    networks:
      - guac_internal_net
    environment:
      - POSTGRES_DB=guac
      - POSTGRES_USER=guac
      - POSTGRES_PASSWORD=guac
    volumes:
      - ./dgraph-stack/guac-data:/var/lib/postgresql/data
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U guac -d guac"]
      interval: 10s
      timeout: 5s
      retries: 5

  # NATS is kept for potential use by collectors, though the core graphql
  # service no longer uses it directly with the 'ent' backend.
  guac-nats:
    image: nats:2.9
    container_name: guac-nats
    networks:
      - guac_internal_net
    restart: on-failure

  # The collectsub service gathers data from various collectors.
  guac-collectsub:
    image: ghcr.io/guacsec/guac:v1.0.0
    container_name: guac-collectsub
    command: "/opt/guac/guaccsub"
    networks:
      - guac_internal_net
    restart: on-failure
    depends_on:
      - guac-nats

  # The graphql service, configured to use the 'ent' backend with Postgres.
  guac-graphql:
    image: ghcr.io/guacsec/guac:v1.0.0
    container_name: guac-graphql
    command: >
      /opt/guac/guacgql
      --gql-backend ent
      --db-driver postgres
      --db-address "postgres://guac:guac@guac-postgres:5432/guac?sslmode=disable"
      --gql-debug
    networks:
      - guac_internal_net
    restart: on-failure
    depends_on:
      guac-postgres:
        condition: service_healthy
    volumes:
      - ../sboms:/sboms

networks:
  guac_internal_net:
    driver: bridge