# compose/mesh.yml

services:
  guac-mesh-graphql:
    build: ../guac-mesh-graphql
    container_name: guac-mesh-graphql
    networks:
      - guac_internal_net
      - graphtastic_net
    ports:
      - "4000:4000"
    volumes:
      - ../guac-mesh-graphql/.meshrc.yml:/usr/src/app/.meshrc.yml
      - ./dgraph-stack/mesh-cache:/usr/src/app/.mesh

networks:
  graphtastic_net:
    external: true
